/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Laurie' at '22/10/15 09:34' with Gradle 2.6
 *
 * @author Laurie, @date 22/10/15 09:34
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
